name: Dispatcher

on:
  push:
    branches: [test-gh-action]

jobs:
  dispatch_event:
    name: Dispatch event
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "trigger"}' https://api.github.com/repos/backpackerhh/backpackerhh/dispatches
